# Generated by Django 3.2.16 on 2022-10-19 05:32

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMaster',
            fields=[
                ('memberId', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranSum',
            fields=[
                ('trId', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('fy', models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029')], max_length=9, verbose_name='fy')),
                ('againstType', models.CharField(choices=[('Shares', 'Shares'), ('Mutual Funds', 'Mutual Funds'), ('Futures & Options', 'Futures & Options'), ('Day Trading', 'Day Trading'), ('Trading', 'Trading')], max_length=20, verbose_name='type')),
                ('sp', models.CharField(max_length=5, verbose_name='scriptId')),
                ('part', models.CharField(max_length=30, verbose_name='script')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('fmr', models.FloatField(blank=True, null=True)),
                ('isinCode', models.CharField(blank=True, max_length=30, null=True)),
                ('trDate', models.DateField(verbose_name='purchaseDate')),
                ('qty', models.IntegerField(verbose_name='quantity')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=65, verbose_name='rate')),
                ('sVal', models.DecimalField(decimal_places=2, max_digits=65, verbose_name='value')),
                ('sttCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True, verbose_name='stt')),
                ('otherCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True, verbose_name='other')),
                ('noteAdd', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('marketRate', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('marketValue', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('HoldingValue', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('avgRate', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('scriptSno', models.IntegerField(blank=True, null=True)),
                ('empCode', models.CharField(blank=True, max_length=10, null=True)),
                ('clDate', models.DateField(blank=True, null=True)),
                ('clRate', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('clQTY', models.IntegerField(blank=True, null=True)),
                ('clValue', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('clsttCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('clOtherCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('balQty', models.IntegerField(blank=True, null=True)),
                ('dayTrade', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('strategyDate', models.DateField(blank=True, null=True)),
                ('strategyTrigger', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, verbose_name='username')),
                ('group', models.CharField(max_length=10)),
                ('firstName', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('lastName', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=40, verbose_name='email address')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('dob', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customer_photo')),
                ('address', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('companyCode', models.CharField(blank=True, max_length=30, null=True)),
                ('swCustomerId', models.IntegerField(blank=True, null=True)),
                ('registrationDate', models.DateField(blank=True, null=True)),
                ('valid_date', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'CustomerMaster',
                'verbose_name_plural': 'CustomerMasters',
            },
        ),
    ]
