# Generated by Django 3.2.16 on 2022-11-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transum',
            name='trDate',
            field=models.DateField(),
        ),
    ]
