# Generated by Django 3.2.16 on 2022-10-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transum',
            name='balQty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
