# Generated by Django 4.1.3 on 2022-11-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transum_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transum',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transum',
            name='entry_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
