# Generated by Django 3.2.16 on 2022-10-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transum_balqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transum',
            name='balQty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
