# Generated by Django 3.2.16 on 2022-11-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mos_sales_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mos_sales',
            name='fno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='mos_sales',
            name='ltgc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='mos_sales',
            name='other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='mos_sales',
            name='purSno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mos_sales',
            name='scriptSno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mos_sales',
            name='speculation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='mos_sales',
            name='stgc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='mos_sales',
            name='stt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
    ]
