# Generated by Django 3.2.16 on 2022-10-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transum_balqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transum',
            name='HoldingValue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='transum',
            name='againstType',
            field=models.CharField(choices=[('Shares', 'Shares'), ('Mutual Funds', 'Mutual Funds'), ('Futures & Options', 'Futures & Options'), ('Day Trading', 'Day Trading'), ('Trading', 'Trading')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transum',
            name='avgRate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='transum',
            name='clOtherCharges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='transum',
            name='clQTY',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transum',
            name='clRate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='transum',
            name='clValue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='transum',
            name='clsttCharges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='transum',
            name='dayTrade',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='transum',
            name='fy',
            field=models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029')], max_length=9),
        ),
        migrations.AlterField(
            model_name='transum',
            name='marketRate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='transum',
            name='marketValue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='transum',
            name='noteAdd',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='transum',
            name='otherCharges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='transum',
            name='part',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transum',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transum',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='transum',
            name='sVal',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='transum',
            name='sp',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='transum',
            name='sttCharges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='transum',
            name='trDate',
            field=models.DateField(),
        ),
    ]
