# Generated by Django 3.2.16 on 2022-11-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transum_trdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transum',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transum',
            name='trDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
