# Generated by Django 3.2.16 on 2022-11-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221107_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermaster',
            options={'verbose_name': 'CustomerMaster', 'verbose_name_plural': 'CustomerMaster'},
        ),
        migrations.AlterModelOptions(
            name='membermaster',
            options={'verbose_name': 'MemberMaster', 'verbose_name_plural': 'CustomerMaster'},
        ),
    ]
