# Generated by Django 3.2.16 on 2022-11-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221107_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membermaster',
            options={'verbose_name': 'MemberMaster', 'verbose_name_plural': 'MemberMaster'},
        ),
    ]
