# Generated by Django 3.2.16 on 2022-10-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221031_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='customer_photo'),
        ),
    ]
