# Generated by Django 3.2.16 on 2022-11-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_transum_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mos_sales',
            options={'verbose_name': 'MOS_Sales', 'verbose_name_plural': 'MOS_Sales'},
        ),
    ]
