# Generated by Django 3.2.16 on 2022-10-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customermaster_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='customer_photo'),
        ),
    ]
