# Generated by Django 3.2.16 on 2022-10-31 10:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customermaster_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transum',
            name='marketValue',
            field=models.FloatField(blank=True, null=True, validators=[api.models.TranSum.validate_decimals]),
        ),
    ]
