# Generated by Django 3.2.16 on 2022-11-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customermaster_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transum',
            name='strategyTrigger',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
