# Generated by Django 3.2.16 on 2022-11-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_transum_marketvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='emailId',
            field=models.EmailField(blank=True, max_length=40, verbose_name='emailId'),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='group',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
