# Generated by Django 3.2.16 on 2022-11-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20221101_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermaster',
            name='group',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
