# Generated by Django 3.2.16 on 2022-11-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_membermaster_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='photo',
            field=models.ImageField(blank=True, default='-', upload_to='customer_photo'),
        ),
    ]
