# Generated by Django 3.2.16 on 2022-11-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_transum_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transum',
            name='scriptSno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
