# Generated by Django 3.2.16 on 2022-11-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_transum_scriptsno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transum',
            name='trDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
